train:
  data_source: patch_pt
  index_csv: outputs/index/index.csv
  train_index_csv: outputs/index/index_train.csv
  val_index_csv: outputs/index/index_val.csv
  test_index_csv: outputs/index/index_test.csv
  patch_pt_root: outputs/patch_pt
  checkpoint_dir: outputs/checkpoints
  log_dir: outputs/logs
  batch_size: 4096
  num_workers: 32
  pin_memory: true
  persistent_workers: true
  patch_shuffle_files: false
  patch_shuffle_within_file: false
  epochs: 20
  lr: 1.0e-4
  weight_decay: 1.0e-5
  device: cuda:3
  strict_cuda: true
  amp: true
  tf32: true
  seed: 42
  sample_fraction: 1.0
  max_samples_per_split: 0

model:
  type: clay_transfer
  clay_ckpt_path: "/JBOD/Lab_data/suhwankim/jbnu_kma_ksh_ta/TA_2D_VER1/src/data/weight/clay-v1.5.ckpt"
  freeze_encoder: true
  bt_waves_um: [3.8, 6.3, 6.9, 7.3, 8.7, 9.6, 10.5, 11.2, 12.3, 13.3]
  rf_waves_um: [0.47, 0.51, 0.64, 0.86, 1.37, 1.6]
  hidden_dim: 256
  dropout: 0.1

data:
  input_stats_path: data/statistics/input_statistics_2022.json
  target_stats_path: data/statistics/statistics_2022.json
  dem_path: data/sub/dem/world_SRTM_dem_ko020lc.bin
  lsmask_path: data/sub/lsmask/lsmask_ko020lc.bin
  latlon_nc_path: data/sub/gk2a_ami_ko020lc_latlon.nc
  image_size: 900
  chip_channels: 19
  patch_size: 9
  time_dim: 7
  loc_dim: 3
  landcover_dim: 17
  gsd_m: 2000.0
  target_unit_in_label: K
  target_stats_unit: K
  celsius_to_kelvin_offset: 273.15
